### ISSUE TITLE
This error is popping up so much in console but the plugin works

### ISSUE THREAD

**Issue by Lazyas** [xRoier/WHLogs#1]
soooo plugin works but when i want to work with console; this error pops up so f*cking much i can't see what i am writing can you fix this?
![image](https://user-images.githubusercontent.com/85154303/148650501-4c2a1d07-4afe-4af4-b74b-e2aae71cac14.png)

**Comment by Lazyas** [comment]
like it pops up 7 errors in 4 seconds

**Comment by xRoier** [comment]
The plugin is not updated, don't use it or just ignore the error
